.github/workflows/build.yaml
Dockerfile

Build on commit and make the PDF available automatically

Add GitHub actions

---

chapters/00-header.md

Change the font, text size, margins, paper size, etc.

Add more formatting

---

chapters/00-header.md

These should make it easier to keep track of how we format things.

Add LaTeX commands for common types

---

Dockerfile
chapters/00-header.md
include/dice.sty

Thanks to @yjyao for writing [yjyao/dice.tex](https://github.com/yjyao/dice.tex)!

Add ability to use dice in text

---

chapters/01-introduction.md

I took a stab at writing the first two paragraphs. My goal is to take our "What is an RPG?" and "How do you play?" and "What is MiniFate?" and condense it down into about half a page.
Big question: What next?!

Draft: Intro

---

.gitignore
Makefile
chapters/00-header.md
chapters/01-introduction.md

side footnotes in boxes

---

loose-notes/01-introduction.md
loose-notes/06-aspects-fate-points.md
loose-notes/07-actions.md
loose-notes/09-thanks.md
loose-notes/at_a_glance.md

Looks like we decided "throw" was the verb for dice, so applying that from 5 years ago. Couple other rewordings.
These all hit the loose notes, so nothing in "prod".

Pull forward old edits

---

chapters/01-introduction.md
style.css

This does not effect PDF rendering at all.

Switch to <img> for dice, and add alt text

---

chapters/02-world-building.md
chapters/03-character-creation.md
loose-notes/04-example-pcs.md

Here is the first stab.
I don't think we should have duplicate skills; what is Tor Byorn's replacement for _Agility_?
Also, should we explain the thought process:
> Naka's player wants to be able to fly and throw fireballs, everything else is secondary. She takes _Shoot_ and flavors it with her concept...

Draft: Example Characters

---

_chapters/00-header.md
_chapters/01-introduction.md
_chapters/02-world-building.md
_chapters/03-character-creation.md
_chapters/04-dice-and-points.md
_chapters/99-scratch.md
_layouts/default.html
assets/_sass/main.scss
index.md

Change fonts to Palatino, Helvetica, and 1.5 line

---

_chapters/03-character-creation.md

This is going to need iteration! I can't get away from the kids long enough to really get into the writing flow, but better to have some words down than none!

Add NPC section

---

_chapters/01-introduction.md
_layouts/default.html
_layouts/substitute.html
assets/_sass/main.scss

Taken from:
https://sylvaindurand.org/improving-typography-on-jekyll/

Add text replacement example

---

assets/_sass/main.scss

From:
To:
Don't love the colors, but it's a start.

Dev aspects skills

---

_chapters/01-introduction.md
_chapters/02-world-building.md
_chapters/03-character-creation.md
_chapters/04-dice-and-points.md

Some general edits for our first few chapters.

Typo Hunting and Reworking

---

assets/_sass/main.scss

Not sure I love the background color.
This will:
- Add a little space between dice in a roll span.
- Change the line on a block quote to be thinner and darker.
- Add a background color to block quotes.
- Move headings down closer to their text (leaving the space above).

Adjust some more CSS

---

_chapters/04-dice-and-points.md

Still need to write more. Are the examples too long?

Writing about Fate Points

---

_chapters/01-introduction.md
_chapters/02-world-building.md
_chapters/03-character-creation.md
_chapters/04-dice-and-points.md
_config.yml
_layouts/substitute.html
index.md

This will allow us to change our name in one line when we figure out
issue #67.

Add name variable and substitution

---

assets/_sass/main.scss

Add dashes instead of bullets

---

_chapters/05-aspects-and-fate-points.md
_loose-notes/06-aspects-fate-points.md

Add aspect intro

---

Dockerfile
Gemfile
Makefile
README.md
_config.yml

Was broken. Copy-pasted over from my config on charles.uno and now it works. Possible some of these gems are not necessary.

Fix docker setup

---

_chapters/00-outline.md
_chapters/01-introduction.md

Bringing over some of the old material section.
In the other section we sort of talk about rolling but I guess that waits for later. I didn't bring over the character sheet section, trying to keep it light and I think that belongs where we talk about character creation?

Adapting the material section

---

_chapters/06-combat-and-conflicts.md

I hear you like examples so I wrote a huge huge huge example. :-/

Draft of challenges

---

_chapters/00-outline.md
assets/_sass/main.scss

not sure if I'll have time for more iteration later. probably worthwhile to get this out there for feedback

First notes on getting started, aspects

---

_chapters/00-outline.md
_chapters/02-world-building.md
_chapters/03-character-creation.md

Starting to work on these.
I'm trying to write short sentences, but I think I'm too committed to it. It feels unnatural in some places.
How many examples do we want in the text? They make it longer but I think it feels really sterile without them.

World building and character creation

---

_chapters/00-outline.md
_chapters/01-introduction.md
_chapters/03-character-creation.md

what the main points are, grouped roughly into what the paragraphs will look like.
grabbed some ideas from the previous text, then deleted the old stuff
also iterated on "Who You Need" section

rough outline for aspects intro

---

_chapters/00-outline.md

Merge if you like, toss otherwise

little fixes

---

_chapters/00-outline.md
_chapters/02-world-building.md
_chapters/03-character-creation.md
_chapters/04-dice-and-points.md
_chapters/05-aspects-and-fate-points.md
_chapters/06-combat-and-conflicts.md
_layouts/substitute.html

I was stuck on a 4 hour flight with no wifi so... Here.

World, PC, and NPC examples

---

_chapters/00-outline.md
_chapters/03-character-creation.md

Split out from the last PR (#89) for additional comments.

Add character examples

---

_chapters/00-outline.md
_chapters/04-dice-and-points.md
_chapters/05-aspects-and-fate-points.md
_chapters/06-combat-and-conflicts.md
_layouts/substitute.html

Need more "mechanics" in the conflicts part I think... But I'm sort of waiting to see what's covered in Dice rolling.

Conflicts and Stress

---

_chapters/00-outline.md

I'm starting to apply the design decisions we talked about. Still don't have the exact details of how harm and consequences works.

Start ripping out ratings and shifts

---

_chapters/00-outline.md

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/MiniFate/MiniFate/pull/104).
* __->__ #104
Writing about rolls (warning: ugly)
Awkward to talk about invoking aspects before we have explained what that means.
A bunch of questions for things that are not settled. Some places I think one way makes sense, other places less clear.
Mostly rough notes and bullets rather than actual prose
But I'm way overdue for a PR and this is something!

Writing about rolls (warning: ugly)

---

_chapters/00-outline.md

Chewed through some TODOs and bullet points in setting creation and PC creation. Tightened up some prose, pulled example aspects into the pirate setting

tidy up setting and pc creation

---

_chapters/00-outline.md

Cleanup Aspects

---

_chapters/00-outline.md

Some incremental updates, tidy up a few todos

back at it!

---

_chapters/00-outline.md

Heavy rewrite, and added some questions.

Updating the "Rolls" section

---

_chapters/00-outline.md

Tried to add a bit about invoking.

Invocations

---

_chapters/00-outline.md

We have a few magic numbers floating around:
- Refresh
- How many stress boxes
- Base bonus for on-character rolls
Let's condense those all into a PC level. The idea of a character level is already baked into the RPG lexicon. Might as well take advantage of it
Changes:
- Significant updates to character creation
- Added a character advancement section
- Nuked the appendix, since character advancement was the only "real" part
- Updated rolls, but that section is still pretty rough

condense magic numbers into a level

---

_chapters/00-outline.md

No rules changes. Just tightening up what we have, trying to get back into it

Iterate on aspects

---

_chapters/00-outline.md

Writing up a bit on invoking and compelling.

Invoke and Compel

---

_chapters/00-outline.md

I guess I need a sentence like "The GM's NPCs can also attack people..."

Trying to add opposed vs unopposed rolls

---

_chapters/00-outline.md
_layouts/substitute.html

Plus some other clean ups, all from #119.
Big change is "Level" to "Rank" (and add a variable). Level's traditionally start at 1, but ours starts at 2.

Update rolls section and TBY example

---

_chapters/00-outline.md
_layouts/substitute.html

Adding in examples to break up blocks of text.

Adding Asepct Example
